package com.sesxh.hoschange.loader;

// Generated 2012-8-23 10:55:59 by Hibernate Tools 3.4.0.CR1


/**
 * DbInfo generated by hbm2java
 */
public class DbInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dbid;
	private String dbname;
	private String useflag;
	private String note;

	public DbInfo() {
	}

	public DbInfo(String dbid, String dbname) {
		this.dbid = dbid;
		this.dbname = dbname;
	}

	public DbInfo(String dbid, String dbname, String useflag, String note) {
		this.dbid = dbid;
		this.dbname = dbname;
		this.useflag = useflag;
		this.note = note;
	}

	public String getDbid() {
		return this.dbid;
	}

	public void setDbid(String dbid) {
		this.dbid = dbid;
	}

	public String getDbname() {
		return this.dbname;
	}

	public void setDbname(String dbname) {
		this.dbname = dbname;
	}

	public String getUseflag() {
		return this.useflag;
	}

	public void setUseflag(String useflag) {
		this.useflag = useflag;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
