package com.sesxh.hoschange.biz.tmg.model;

import java.util.Date;

/**
 * TaskSchedulerLog generated by hbm2java
 */
public class TaskSchedulerLog implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String rzid;
	private String tsid;
	private Date qssj;
	private Date zzsj;
	private String cgbz;
	private String sm;

	public String getRzid() {
		return this.rzid;
	}

	public void setRzid(String rzid) {
		this.rzid = rzid;
	}

	public String getTsid() {
		return this.tsid;
	}

	public void setTsid(String tsid) {
		this.tsid = tsid;
	}

	public Date getQssj() {
		return this.qssj;
	}

	public void setQssj(Date qssj) {
		this.qssj = qssj;
	}

	public Date getZzsj() {
		return this.zzsj;
	}

	public void setZzsj(Date zzsj) {
		this.zzsj = zzsj;
	}

	public String getCgbz() {
		return this.cgbz;
	}

	public void setCgbz(String cgbz) {
		this.cgbz = cgbz;
	}

	public String getSm() {
		return this.sm;
	}

	public void setSm(String sm) {
		this.sm = sm;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
