package com.sesxh.hoschange.biz.tmg.model;

// default package

// Generated 2012-8-27 14:38:15 by Hibernate Tools 3.4.0.CR1

/**
 * TaskScheduler generated by hbm2java
 */
public class TaskScheduler implements java.io.Serializable, Cloneable {

	private static final long serialVersionUID = 7097992488678207915L;

	private String tsid;
	private String appid;
	private String rwid;
	private String rwmc;
	private String rwnrlx;
	private String rwnr;
	private String zxjh;
	private String rwcs;
	private String yxbz;

	public String getTsid() {
		return this.tsid;
	}

	public void setTsid(String tsid) {
		this.tsid = tsid;
	}

	public String getAppid() {
		return this.appid;
	}

	public void setAppid(String appid) {
		this.appid = appid;
	}

	public String getRwid() {
		return this.rwid;
	}

	public void setRwid(String rwid) {
		this.rwid = rwid;
	}

	public String getRwmc() {
		return this.rwmc;
	}

	public void setRwmc(String rwmc) {
		this.rwmc = rwmc;
	}

	public String getRwnrlx() {
		return this.rwnrlx;
	}

	public void setRwnrlx(String rwnrlx) {
		this.rwnrlx = rwnrlx;
	}

	public String getRwnr() {
		return this.rwnr;
	}

	public void setRwnr(String rwnr) {
		this.rwnr = rwnr;
	}

	public String getZxjh() {
		return this.zxjh;
	}

	public void setZxjh(String zxjh) {
		this.zxjh = zxjh;
	}

	public String getRwcs() {
		return this.rwcs;
	}

	public void setRwcs(String rwcs) {
		this.rwcs = rwcs;
	}

	public String getYxbz() {
		return this.yxbz;
	}

	public void setYxbz(String yxbz) {
		this.yxbz = yxbz;
	}

	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
